name: Deploy to Azure Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AFPHEOCNETSECRET }}

      - name: Deploy to Azure Spring Boot
        run: az spring-boot app deploy --name afrpheocnet --resource-group PHEOC-P-EUW-RG01 --jar-path target/afrpheocnet.jar --jvm-options '-Xms512m -Xmx1024m'
